- name: EC2
  hosts: publicEc2
  tasks:
  - name: create private ec2
    ec2:
      key_name: ansible
      region: us-east-1
      instance_type: t2.micro
      image: ami-05548f9cecf47b442
      instance_tags:
        Name: private_ec2
      network:
        vpc_id: vpc-014241ae95838a0ee
        vpc_subnet_id: subnet-0f77b074a1a2f2454
        assign_public_ip: no
      count: 1
