- name: EC2
  hosts: localhost
  tasks:
  # - name: Ensure boto and boto3 modules are installed
  #   pip:
  #     name: "{{ item }}"
  #   with_items:
  #     - boto3
  #     - botocore
  #   delegate_to: 18.212.26.130

  - name: create private ec2
    amazon.aws.ec2_instance:
      name: private_ec2
      key_name: ansible
      region: us-east-1
      instance_type: t2.micro
      image_id: ami-053b0d53c279acc90
      vpc_subnet_id: subnet-0f77b074a1a2f2454
      security_group: sg-0926613821c4df4ba
      exact_count: 1
      secret_key: "{{ AWS_SECRET_ACCESS }}"
    register: private_ec2

  - ansible.builtin.pause:
      seconds: 30
  - name: Add the private EC2 instance to the host group
    template:
        src: template.j2
        dest: inventory.yaml
    become: yes

  - name: Print the full output
    ansible.builtin.debug:
      var: private_ec2
